/**
 * @file HTML Tree Builder
 * Transforms a flat token stream into a hierarchical custom AST DOM tree.
 */

/**
 * Builds a custom AST root array from token stream.
 * @param {Array<Object>} tokens - Array of tokens generated by `tokenize()`.
 * @returns {Array<Object>} Root AST node array representing parsed DOM structure.
 */
export function buildTree(tokens) {
    const root = [];

    const stack = [
        {
            type: "root",
            children: root,
        },
    ];

    for (const token of tokens) {
        if (token.type === "text") {
            appendChild(stack, token);
        } else if (token.type === "comment") {
            appendChild(stack, {
                type: "comment",
                value: token.value,
            });
        } else if (token.type === "doctype") {
            appendChild(stack, {
                type: "doctype",
                value: token.value,
            });
        } else if (token.type === "startTag") {
            const elementNode = {
                type: "element",
                tagName: token.tagName,
                attributes: token.attributes,
                children: [],
            };

            if (token.isSelfClosing) {
                elementNode.isSelfClosing = true;
            }

            appendChild(stack, elementNode);

            if (!token.isSelfClosing) {
                stack.push(elementNode);
            }
        } else if (token.type === "endTag") {
            let matchIndex = -1;
            const lowerEndTag = token.tagName.toLowerCase();

            for (let i = stack.length - 1; i > 0; i--) {
                if (stack[i].tagName.toLowerCase() === lowerEndTag) {
                    matchIndex = i;
                    break;
                }
            }

            if (matchIndex !== -1) {
                for (let i = stack.length - 1; i > matchIndex; i--) {
                    stack[i].isUnclosed = true;
                }

                stack.length = matchIndex;
            } else {
                appendChild(stack, {
                    type: "text",
                    value: `</${token.tagName}>`,
                });
            }
        }
    }

    for (let i = 1; i < stack.length; i++) {
        stack[i].isUnclosed = true;
    }

    return root;
}

/**
 * Appends a node to the children array of the current stack frame.
 * @param {Array<Object>} stack
 * @param {Object} node
 * @returns {void}
 */
function appendChild(stack, node) {
    const parent = stack[stack.length - 1];

    parent.children.push(node);
}